apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rptx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-rptx@sha256:75dcd4471db4f8bb0a77f3afb73286826af7ab769e94ccd052b1939a3d4a0cc5
        name: my-nodejs
        resources: {}
status: {}
